package com.dci.hrms.report.employeeEarlyStart;

public class EmployeeEarlyStartQueryUtil {

	public static String getHospitalList = "select distinct cu.company_code as id, c.company_name as text from company_user cu join company c on c.company_id = cu.company_code join user_rights ur on ur.company_user_id = cu.company_user_id " + "join form_property fp on fp.form_property_id  = ur.form_property_id where fp.form_code = ? and cu.user_id = ?";
	public static String get_EmployeeEarlyStartSingle_List = "SELECT D.Department_Name AS departmentName, to_char(A.Date,'dd/MM/yyyy') as date,A.Start_Time AS shiftStartTime,A.ShiftName as shiftName, " + "A.End_Time AS shiftEndTime, A.Employee_Id as employeeId, E.First_Name as employeeName, Intime AS intime, outTime AS outTime , " + "case when extract (minute from ( to_timestamp(Start_Time,'dd/mm/yyyy hh24:mi') - to_timestamp(Intime,'dd/mm/yyyy hh24:mi')) ) "
			+ "<= 0 then 0 else extract (minute from ( to_timestamp(Start_Time,'dd/mm/yyyy hh24:mi')- to_timestamp(Intime,'dd/mm/yyyy hh24:mi')) ) end || ' mins' as lateBy, " + "case when extract (hour from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi') - to_timestamp(outTime,'dd/mm/yyyy hh24:mi') ) ) " + "<= 0 then 0 else extract (hour from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi')- to_timestamp(outTime,'dd/mm/yyyy hh24:mi') )) end || ' hours ' || "
			+ "case when extract (minute from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi') - to_timestamp(outTime,'dd/mm/yyyy hh24:mi') ) ) " + "<= 0 then 0 else extract (minute from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi')- to_timestamp(outTime,'dd/mm/yyyy hh24:mi') )) end || ' mins' as earlyStart, " + "case when extract (minute from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi') - to_timestamp(outTime,'dd/mm/yyyy hh24:mi'))) > -1 then 'Early Start' else null end as status "
			+ "from vw_datewise_attendance A, Employee E,Department D where A.Employee_Id = E.Employee_Id AND E.Department_ID=D.Department_ID and DATE = ? AND " + "A.Employee_Id in (select employee_id from vw_employee_branch where Branch_ID =? ) " + "AND case when extract (minute from ( to_timestamp(early_exit,'dd/mm/yyyy hh24:mi') - to_timestamp(outTime,'dd/mm/yyyy hh24:mi') ) ) " + "<= 0 then null else extract (minute from ( to_timestamp(early_exit,'dd/mm/yyyy hh24:mi')- to_timestamp(outTime,'dd/mm/yyyy hh24:mi') )) "
			+ "end IS NOT NULL ORDER BY E.First_Name";

	public static String get_EmployeeEarlyStartMultiple_List = "SELECT D.Department_Name AS departmentName, to_char(A.Date,'dd/MM/yyyy') as date,A.Start_Time AS shiftStartTime,A.ShiftName as shiftName, " + "A.End_Time AS shiftEndTime, A.Employee_Id as employeeId, E.First_Name as employeeName, Intime AS intime, outTime AS outTime , " + "case when extract (minute from ( to_timestamp(Start_Time,'dd/mm/yyyy hh24:mi') - to_timestamp(Intime,'dd/mm/yyyy hh24:mi')) ) "
			+ "<= 0 then 0 else extract (minute from ( to_timestamp(Start_Time,'dd/mm/yyyy hh24:mi')- to_timestamp(Intime,'dd/mm/yyyy hh24:mi')) ) end || ' mins' as lateBy, " + "case when extract (hour from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi') - to_timestamp(outTime,'dd/mm/yyyy hh24:mi') ) ) " + "<= 0 then 0 else extract (hour from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi')- to_timestamp(outTime,'dd/mm/yyyy hh24:mi') )) end || ' hours ' || "
			+ "case when extract (minute from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi') - to_timestamp(outTime,'dd/mm/yyyy hh24:mi') ) ) " + "<= 0 then 0 else extract (minute from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi')- to_timestamp(outTime,'dd/mm/yyyy hh24:mi') )) end || ' mins' as earlyStart, " + "case when extract (minute from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi') - to_timestamp(outTime,'dd/mm/yyyy hh24:mi'))) > -1 then 'Early Start' else null end as status "
			+ "from vw_datewise_attendance A, Employee E,Department D where A.Employee_Id = E.Employee_Id AND E.Department_ID=D.Department_ID and DATE >= ? and DATE <= ? " + " and A.Employee_Id in (select employee_id from vw_employee_branch where Branch_ID =? ) " + "AND case when extract (minute from ( to_timestamp(early_exit,'dd/mm/yyyy hh24:mi') - to_timestamp(outTime,'dd/mm/yyyy hh24:mi') ) ) " + "<= 0 then null else extract (minute from ( to_timestamp(early_exit,'dd/mm/yyyy hh24:mi')- to_timestamp(outTime,'dd/mm/yyyy hh24:mi') )) "
			+ "end IS NOT NULL ORDER BY E.First_Name";

	public static String get_EmployeeLateStartSingle_List = "SELECT D.Department_Name AS departmentName, to_char(A.Date,'dd/MM/yyyy') as date,A.Start_Time AS shiftStartTime,A.ShiftName as shiftName, " + "A.End_Time AS shiftEndTime, A.Employee_Id as employeeId, E.First_Name as employeeName, Intime AS intime, outTime AS outTime , " + "case when extract (hour from ( to_timestamp(Intime,'dd/mm/yyyy hh24:mi') - to_timestamp(Start_Time,'dd/mm/yyyy hh24:mi') ) ) "
			+ "<= 0 then 0 else extract (hour from ( to_timestamp(Intime,'dd/mm/yyyy hh24:mi')- to_timestamp(Start_Time,'dd/mm/yyyy hh24:mi') )) end || ' hours ' || " + "case when extract (minute from ( to_timestamp(Intime,'dd/mm/yyyy hh24:mi') - to_timestamp(Start_Time,'dd/mm/yyyy hh24:mi')) ) " + "<= 0 then 0 else extract (minute from ( to_timestamp(Intime,'dd/mm/yyyy hh24:mi')- to_timestamp(Start_Time,'dd/mm/yyyy hh24:mi')) ) end || ' mins' as lateBy, "
			+ "case when extract (hour from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi') - to_timestamp(outTime,'dd/mm/yyyy hh24:mi') ) ) " + "<= 0 then 0 else extract (hour from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi')- to_timestamp(outTime,'dd/mm/yyyy hh24:mi') )) end || ' hours ' || " + "case when extract (minute from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi') - to_timestamp(outTime,'dd/mm/yyyy hh24:mi') ) ) "
			+ "<= 0 then 0 else extract (minute from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi')- to_timestamp(outTime,'dd/mm/yyyy hh24:mi') )) end || ' mins' as earlyStart, " + "case when extract (minute from ( to_timestamp(Intime,'dd/mm/yyyy hh24:mi') - to_timestamp(Start_Time,'dd/mm/yyyy hh24:mi'))) > -1 then 'Late' else null end as status " + "from vw_datewise_attendance A, Employee E,Department D where A.Employee_Id = E.Employee_Id AND E.Department_ID=D.Department_ID and DATE = ? AND "
			+ "A.Employee_Id in (select employee_id from vw_employee_branch where Branch_ID =? ) " + "AND case when extract (minute from ( to_timestamp(Intime,'dd/mm/yyyy hh24:mi') - to_timestamp(late_after,'dd/mm/yyyy hh24:mi') ) ) " + "<= 0 then null else extract (minute from ( to_timestamp(Intime,'dd/mm/yyyy hh24:mi')- to_timestamp(late_after,'dd/mm/yyyy hh24:mi') )) " + "end IS NOT NULL ORDER BY E.First_Name";

	public static String get_EmployeeLateStartMultiple_List = "SELECT D.Department_Name AS departmentName, to_char(A.Date,'dd/MM/yyyy') as date,A.Start_Time AS shiftStartTime,A.ShiftName as shiftName, " + "A.End_Time AS shiftEndTime, A.Employee_Id as employeeId, E.First_Name as employeeName, Intime AS intime, outTime AS outTime , " + "case when extract (hour from ( to_timestamp(Intime,'dd/mm/yyyy hh24:mi') - to_timestamp(Start_Time,'dd/mm/yyyy hh24:mi') ) ) "
			+ "<= 0 then 0 else extract (hour from ( to_timestamp(Intime,'dd/mm/yyyy hh24:mi')- to_timestamp(Start_Time,'dd/mm/yyyy hh24:mi') )) end || ' hours ' || " + "case when extract (minute from ( to_timestamp(Intime,'dd/mm/yyyy hh24:mi') - to_timestamp(Start_Time,'dd/mm/yyyy hh24:mi')) ) " + "<= 0 then 0 else extract (minute from ( to_timestamp(Intime,'dd/mm/yyyy hh24:mi')- to_timestamp(Start_Time,'dd/mm/yyyy hh24:mi')) ) end || ' mins' as lateBy, "
			+ "case when extract (hour from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi') - to_timestamp(outTime,'dd/mm/yyyy hh24:mi') ) ) " + "<= 0 then 0 else extract (hour from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi')- to_timestamp(outTime,'dd/mm/yyyy hh24:mi') )) end || ' hours ' || " + "case when extract (minute from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi') - to_timestamp(outTime,'dd/mm/yyyy hh24:mi') ) ) "
			+ "<= 0 then 0 else extract (minute from ( to_timestamp(End_Time,'dd/mm/yyyy hh24:mi')- to_timestamp(outTime,'dd/mm/yyyy hh24:mi') )) end || ' mins' as earlyStart, " + "case when extract (minute from ( to_timestamp(Intime,'dd/mm/yyyy hh24:mi') - to_timestamp(Start_Time,'dd/mm/yyyy hh24:mi'))) > -1 then 'Late' else null end as status " + "from vw_datewise_attendance A, Employee E,Department D where A.Employee_Id = E.Employee_Id AND E.Department_ID=D.Department_ID and DATE >= ? and DATE <= ? AND "
			+ "A.Employee_Id in (select employee_id from vw_employee_branch where Branch_ID =? ) " + "AND case when extract (minute from ( to_timestamp(Intime,'dd/mm/yyyy hh24:mi') - to_timestamp(late_after,'dd/mm/yyyy hh24:mi') ) ) " + "<= 0 then null else extract (minute from ( to_timestamp(Intime,'dd/mm/yyyy hh24:mi')- to_timestamp(late_after,'dd/mm/yyyy hh24:mi') )) " + "end IS NOT NULL ORDER BY E.First_Name";

	public static String get_HabitualLate_List = "SELECT  * from (select A.Employee_Id as EmployeeId, E.First_Name as employeeName, D.Department_Name AS DepartmentName, COUNT(*)as noOfDays " + "from vw_datewise_attendance A, Employee E,Department D  where A.Employee_Id = E.Employee_Id  AND E.Department_ID=D.Department_ID AND A.Employee_Id in " + "(select employee_id from vw_employee_branch where Branch_ID = ?) AND DATE >= ? and DATE <= ? and "
			+ "extract (minute from ( to_timestamp(Intime,'dd/mm/yyyy hh24:mi') - to_timestamp(late_after,'dd/mm/yyyy hh24:mi') ) ) > 1 " + "group by A.Employee_Id, E.First_Name, D.Department_Name) T where NoOfDays > 3";

	public static String getEmployeeList = "select concat(first_name,' ',surname) as empName, concat(employee_id,'-',first_name,' ',surname) as text , employee_id as empId , employee_id as id from employee join branch_department on employee.branch_department_id=branch_department.branch_department_id inner join branch on branch.branch_id = branch_department.branch_id inner join company c on c.company_id = branch.company_id where  employee.status = 't' and branch_department.branch_id = ?  and  relieving_date is null order by first_name asc";

	public static String getDivisionList = "select division_id as id,division_name as text from division where company_id = ?";

	public static String getEmployeeListDiv = "select  concat(employee_id,'-',first_name,' ',surname) as text ,employee_id as id from employee where division_id = ?::int  and relieving_date is null and status = true";

	// public static String get_EmployeeDetail_List =
	// "select distinct e.employee_id as employeeId, e.first_name as
	// employeeName, e.gender as gender, d.department_name as departmentName,
	// ld.lab_department_name as labDepartmentName from employee e "
	// +
	// "inner join branch_department bd on
	// bd.branch_department_id=e.branch_department_id inner join branch b on
	// bd.branch_id=b.branch_id "
	// +
	// "inner join department d on b.branch_id=d.branch_id inner join
	// lab_department ld on d.department_id=ld.department_id where
	// b.company_id=? and b.branch_id =? and e.employee_id=?";

	public static String get_leave_summary = "SELECT  Leave_Request.Leave_Type as leaveCode, to_char(Leave_Request.Date_From,'DD/MM/YYYY') AS dateFrom, to_char(Leave_Request.Date_To,'DD/MM/YYYY') AS dateTo, Leave_Request.Number_Of_Days as noOfDays, " + "to_char(Leave_Request.Applied_On,'DD/MM/YYYY') AS appliedOn, Leave_Request_Action.action_by as approvedBy, Leave_Request_Action.status as status FROM  Leave_Request "
			+ "INNER JOIN Leave_Request_Action ON Leave_Request.Leave_Request_Id = Leave_Request_Action.Leave_Request_Id WHERE Leave_Request.Leave_Type=? AND Leave_Request.Employee_Id=? and " + "EXTRACT(YEAR FROM Leave_Request.Date_From )= extract ( year from now())  and EXTRACT(YEAR FROM Leave_Request.Date_To )= extract ( year from now())";

	public static final String get_EmployeeDetail_List = "SELECT  MTable.Employee_Id employeeId,  MTable.EmployeeName employeeName, MTable.Year, MTable.Short_Name as shortName, MTable.leave_type_name AS leaveName ,CAST(MTable.Yearly_Max AS decimal(10,2)) AS AllowedLeave,   CASE WHEN CAST(TransTable.Number_Of_Days AS decimal(10,2))   "
			+ "IS NULL THEN 0 ELSE  CAST(TransTable.Number_Of_Days AS decimal(10,2)) END AS Consumed,   CASE WHEN  CAST(TransTable.Number_Of_Days AS decimal(10,2))   IS NOT NULL THEN (CAST(MTable.Yearly_Max -TransTable.Number_Of_Days AS decimal(10,2))) ELSE CAST((MTable.Yearly_Max - 0)AS decimal(10,2))  END AS Balance	   "
			+ "FROM    (SELECT     Employee_Leave_Type.Yearly_Max, Employee_Leave_Type.Short_Name, Leave_Type.leave_type_Name, Employee_Leave_Type.Year,   Employee.First_Name AS EmployeeName, Employee.Employee_Id   FROM    Employee INNER JOIN   Employee_Leave_Type ON Employee.Employee_Id = Employee_Leave_Type.Employee_Id INNER JOIN   Leave_Type ON Employee_Leave_Type.Short_Name = Leave_Type.Short_Name      WHERE      (Employee.Employee_Id =  ? ) And (Employee_Leave_Type.Year = extract ( year from now())) and leave_Type.status=true and leave_type.gender=0) AS MTable LEFT OUTER JOIN   (SELECT     SUM(Leave_Request.Number_Of_Days) AS Number_Of_Days, Leave_Type.Short_Name, Leave_Type.leave_type_Name   	"
			+ "FROM    Leave_Request INNER JOIN   Leave_Request_Action ON Leave_Request.Leave_Request_Id = Leave_Request_Action.Leave_Request_Id INNER JOIN   Leave_Type ON Leave_Request.Leave_Type = Leave_Type.Short_Name   WHERE      (Leave_Request.Employee_Id = ? ) AND (Leave_Request_Action.status <> 2) and   EXTRACT(YEAR FROM Date_To)= extract ( year from now()) " + "GROUP BY Leave_Type.Short_Name, Leave_Type.leave_type_name) AS TransTable ON TransTable.Short_Name = MTable.Short_Name where MTable.Yearly_Max > 0";

}