package com.dci.common.util;

public class QuantityRateReportQueryUtil {
	/*
	 * public static String QUATITY_VS_RATE =
	 * "select QUOTATION_NO quotationNo,MLO_SHORT_NAME mloshortname,pol,pod,TO_CHAR(QUOTATION_DT,'DD/MM/YYYY') quotationdt,TO_CHAR(VALID_FROM,'DD/MM/YYYY')  validfrom,TO_CHAR(VALID_TILL,'DD/MM/YYYY')  validto,qty quatity, rate  from (select  sum(INVOICE_CON_DTL.qty) qty,sum(INVOICE_CON_DTL.rate) rate,SINGLEINVOICE_HDR.quotation_no ,VIEW_QUOTATION_DETAILS.quotation_dt,"
	 * +
	 * " VIEW_QUOTATION_DETAILS.mlo_short_name,VIEW_QUOTATION_DETAILS.VALID_FROM,VIEW_QUOTATION_DETAILS.VALID_TILL,VIEW_QUOTATION_DETAILS.pol,VIEW_QUOTATION_DETAILS.pod from SINGLEINVOICE_HDR,VIEW_QUOTATION_DETAILS,INVOICE_CON_DTL"
	 * +
	 * " where INVOICE_CON_DTL.INVOICE_NO=SINGLEINVOICE_HDR.INVOICE_NO and SINGLEINVOICE_HDR.QUOTATION_NO=VIEW_QUOTATION_DETAILS.QUOTATION_NO"
	 * +
	 * " and CONTAINER_ID=11 group by   SINGLEINVOICE_HDR.quotation_no ,quotation_dt,mlo_short_name,VALID_FROM,VALID_TILL,pol,pod)   "
	 * ;
	 */

	public static String QUATITY_VS_RATE_LIVE = " select quotationNo,mloshortname,TO_CHAR(VALID_TILL,'MM/DD/YYYY') validto,TO_CHAR(VALID_FROM,'MM/DD/YYYY') validfrom,rateD20,rateD40,quatityD20,quatityD40,rateM20,rateM40,quatityM20,quatityM40,rateR20,rateR40,quatityR20,quatityR40,TO_CHAR(QUOTATION_DT,'MM/DD/YYYY') quotationdt,pol,pod from (select * from "
			+ "(select QUOTATION_NO quotationNo,MLO_SHORT_NAME mloshortname,pol,pod,QUOTATION_DT,"
			+ " VALID_FROM  ,VALID_TILL  ,sum(D20) rateD20 ,sum(D40)"
			+ " rateD40,sum(M20) rateM20 ,sum(M40)"
			+ " rateM40,sum(R20) rateR20 ,sum(R40)"
			+ " rateR40 from VIEW_QUOTATION_DETAILS"
			+ " group by QUOTATION_NO,MLO_SHORT_NAME,pol,pod,QUOTATION_DT,VALID_FROM,VALID_TILL) a,"
			+

			"(select sum(D20r) quatityD20,sum(D40r) quatityD40,sum(M20r) quatityM20,sum(M40r) quatityM40,sum(R20r) quatityR20,sum(R40r) quatityR40,x.QUOTATION_NO  from (select (CASE WHEN container_type_id = 11 "
			+ "	then QUANTITY else 0 end) AS D20r,(CASE WHEN container_type_id = 14"
			+ " then 2*QUANTITY else 0 end) AS D40r ,(CASE WHEN container_type_id = 1 "
			+ "	then QUANTITY else 0 end) AS M20r,(CASE WHEN container_type_id = 2"
			+ " then 2*QUANTITY else 0 end) AS M40r ,(CASE WHEN container_type_id = 24 "
			+ "	then QUANTITY else 0 end) AS R20r,(CASE WHEN container_type_id = 26"
			+ " then 2*QUANTITY else 0 end) AS R40r ,VSI_GI_AMOUNT.QUOTATION_NO,CONTAINER_TYPE_ID from  VSI_GI_AMOUNT,LOADING,loading_container_type where  LOADING_NO=LOADING.LOADING_ID and loading_container_type.LOADING_ID=LOADING.LOADING_ID and loading_container_type.container_type_id in(11,14,1,2,24,26) and  APPROVED_BY is not null) x   group by QUOTATION_NO ) b"
			+ " where a.quotationNo=b.QUOTATION_NO) a ";

	public static String QUATITY_VS_RATE_OLD = "select quotationNo,mloshortname,TO_CHAR(VALID_TILL,'DD/MM/YYYY') validto,TO_CHAR(VALID_FROM,'DD/MM/YYYY') validfrom, "
			+ "			 rateD20,rateD40,quatityD20,quatityD40,rateM20,rateM40,quatityM20,quatityM40,rateR20,rateR40,quatityR20,quatityR40,quatityOOG20,quatityOOG40, "
			+ "			 TO_CHAR(QUOTATION_DT,'MM/DD/YYYY') quotationdt,pol,pod,upper(quotationType) quotationType,sector,rateOOG20,rateOOG40,TO_CHAR(SAILING_DT,'MM/DD/YYYY') sailingdt,created_by from (select   quotationNo, "
			+ "			  mloshortname,a.pol,a.pod,QUOTATION_DT, VALID_FROM  ,VALID_TILL  , SAILING_DT, "
			+ "			   rateD20 , rateD40, rateM20 , "
			+ "			   rateM40, "
			+ "			  rateR20 , rateR40,rateOOG20,rateOOG40,  quatityD20, quatityD40, quatityM20, quatityM40, "
			+ "			 quatityR20, quatityR40,QUOTATION_NO ,quotationType,sector,quatityOOG20,quatityOOG40,created_by  from ( "
			+ " select QUOTATION.QUOTATION_NO quotationNo,QUOTATION.created_by, "
			+ "			 MLO_SHORT_NAME mloshortname,QUOTATION_PORT_PAIR.pol,QUOTATION_PORT_PAIR.pod,QUOTATION_DT, VALID_FROM  ,VALID_TILL  , "
			+ "			   rateD20 , rateD40, rateM20 , "
			+ "			   rateM40, "
			+ "			  rateR20 , rateR40,rateOOG20,rateOOG40, QUOTATION.QUOTATION_TYPE quotationType,sector FROM ( "
			+ "(SELECT  QUOTATION_NO,QPP_ID,sum(CASE WHEN qc.surcharge_id='SC0001'   then coalesce(qc.D20,0) else 0 end ) rateD20 , "
			+ "        sum(CASE WHEN qc.surcharge_id='SC0001'   then coalesce(qc.D40,0) else 0 end ) rateD40, "
			+ "        sum(CASE WHEN qc.surcharge_id='SC0001'   then coalesce(qc.M20,0) else 0 end ) rateM20 , "
			+ "			 sum(CASE WHEN qc.surcharge_id='SC0001'   then coalesce(qc.M40,0) else 0 end ) rateM40, "
			+ "			 sum(CASE WHEN qc.surcharge_id='SC0003'   then coalesce(qc.D20,0) else 0 end ) rateR20 , "
			+ "       sum(CASE WHEN qc.surcharge_id='SC0003'   then coalesce(qc.D40,0) else 0 end ) rateR40, "
			+ "			 sum(CASE WHEN qc.surcharge_id='SC0006'   then coalesce(qc.D20,0) else 0 end ) rateOOG20 , "
			+ "       sum(CASE WHEN qc.surcharge_id='SC0006'   then coalesce(qc.D40,0) else 0 end ) rateOOG40 "

			+ "       from QUOTATION_CONTAINER_CHARGES qc WHERE QUOTATION_NO LIKE 'QO%' GROUP BY QUOTATION_NO,QPP_ID ) "
			+ "       UNION "
			+ "        "
			+ "       (SELECT  QUOTATION_NO,QPP_ID,sum(CASE WHEN qc.surcharge_id='SC0001'   then coalesce(qc.D20,0) else 0 end ) rateD20 , "
			+ "        sum(CASE WHEN qc.surcharge_id='SC0001'   then coalesce(qc.D40,0) else 0 end ) rateD40, "
			+ "        sum(CASE WHEN qc.surcharge_id='SC0001'   then coalesce(qc.M20,0) else 0 end ) rateM20 , "
			+ "			 sum(CASE WHEN qc.surcharge_id='SC0001'   then coalesce(qc.M40,0) else 0 end ) rateM40, "
			+ "			 sum(CASE WHEN qc.surcharge_id='SC0003'   then coalesce(qc.D20,0) else 0 end ) rateR20 , "
			+ "       sum(CASE WHEN qc.surcharge_id='SC0003'   then coalesce(qc.D40,0) else 0 end ) rateR40 ,"
			+ "			 sum(CASE WHEN qc.surcharge_id='SC0006'   then coalesce(qc.D20,0) else 0 end ) rateOOG20 , "
			+ "       sum(CASE WHEN qc.surcharge_id='SC0006'   then coalesce(qc.D40,0) else 0 end ) rateOOG40 "
			+ "       from TRANS_QUOT_CONTAINER_CHARGES qc WHERE QUOTATION_NO LIKE 'QT%' GROUP BY QUOTATION_NO,QPP_ID ) "
			+ "       ) QUOTATION_CONTAINER_CHARGES "
			+ "       Inner join QUOTATION_PORT_PAIR on QUOTATION_CONTAINER_CHARGES.QUOTATION_NO=QUOTATION_PORT_PAIR.QUOTATION_NO "
			+ "			 AND QUOTATION_CONTAINER_CHARGES.QPP_ID=QUOTATION_PORT_PAIR.QPP_ID "
			+ "        Inner join Quotation on Quotation.QUOTATION_NO=QUOTATION_PORT_PAIR.QUOTATION_NO "
			+ "			 left join mlo_master on mlo_code=mlo_id) a, "
			+ "			 (select sum(D20) quatityD20,sum(D40) quatityD40,sum(M20) quatityM20,sum(M40) quatityM40,sum(R20) "
			+ "			 quatityR20,sum(R40) quatityR40,QUOTATION_NO ,pol,pod,SUM(OOG20) quatityOOG20,SUM(OOG40) quatityOOG40,SAILING_DT  from ( "
			+ "			 select loading_id,D20,D40,D45,M20,M40,M45,R20,R40,OOG20,OOG40,APPROVED_BY,QUOTATION_NO,pol,pod,SAILING_DT  from loading_summary loading , "
			+ "			 (SELECT BL.LOADING_NO,BL.BL_NO,DTL.INVOICE_NO,HDR.QUOTATION_NO,HDR.TOTAL, hdr.invoice_dt,HDR.AGENT "
			+ "			 FROM SINGLEINVOICE_BL_DTL DTL,SINGLEINVOICE_HDR HDR,BILL_OF_LADING_HDR BL "
			+ "			 WHERE DTL.INVOICE_NO=HDR.INVOICE_NO AND BL.BL_NO=DTL.BL_NO "
			+ "			) INVOICE  where loading.loading_id=INVOICE.LOADING_NO and  APPROVED_BY is not null "
			+ "			 ) x   group by x.QUOTATION_NO,pol,pod,SAILING_DT   ) b   where a.quotationNo=b.QUOTATION_NO and a.pol=b.pol and a.pod=b.pod   ) a";
	

	public static String QUATITY_VS_RATE_SIN="select terms_of_shipment shipment,quotationNo,mloshortname,TO_CHAR(VALID_TILL,'DD/MM/YYYY') validto,TO_CHAR(VALID_FROM,'DD/MM/YYYY') validfrom, "
			+ "coalesce(rateD20,0) rateD20,coalesce(rateD40,0) rateD40,coalesce(quatityD20,0) quatityD20,coalesce(quatityD40,0) quatityD40,coalesce(rateM20,0) rateM20,"
			+ "coalesce(rateM40,0) rateM40,coalesce(quatityM20,0) quatityM20,coalesce(quatityM40,0) quatityM40,coalesce(rateR20,0) rateR20,coalesce(rateR40,0) rateR40,"
			+ "coalesce(quatityR20,0) quatityR20,coalesce(quatityR40,0) quatityR40,coalesce(quatityOOG20,0) quatityOOG20,coalesce(quatityOOG40,0) quatityOOG40, "
			+ " TO_CHAR(QUOTATION_DT,'MM/DD/YYYY') quotationdt,pol,pod,upper(quotationType) quotationType,sector,coalesce(rateOOG20,0) rateOOG20,coalesce(rateOOG40,0) rateOOG40, "
			+ " TO_CHAR(SAILING_DT,'MM/DD/YYYY') sailingdt,created_by,thcd20,thcd40,thcm20,thcm40 from ( "
			+ " "
			+ "  select * from quatity_rate_report "
			+ " ) a";
	
	public static String QUATITY_VS_RATE_DUBAI="select terms_of_shipment shipment,quotationNo,mloshortname,TO_CHAR(VALID_TILL,'DD/MM/YYYY') validto,TO_CHAR(VALID_FROM,'DD/MM/YYYY') validfrom, "
			+ "coalesce(rateD20+tthcd20,0) rateD20,coalesce(rateD40+tthcd40,0) rateD40,coalesce(quatityD20,0) quatityD20,coalesce(quatityD40,0) quatityD40,coalesce(rateM20+tthcm20,0) rateM20,"
			+ "coalesce(rateM40+tthcm40,0) rateM40,coalesce(quatityM20,0) quatityM20,coalesce(quatityM40,0) quatityM40,coalesce(rateR20,0) rateR20,coalesce(rateR40,0) rateR40,"
			+ "coalesce(quatityR20,0) quatityR20,coalesce(quatityR40,0) quatityR40,coalesce(quatityOOG20,0) quatityOOG20,coalesce(quatityOOG40,0) quatityOOG40, "
			+ " TO_CHAR(QUOTATION_DT,'MM/DD/YYYY') quotationdt,pol,pod,upper(quotationType) quotationType,sector,coalesce(rateOOG20,0) rateOOG20,coalesce(rateOOG40,0) rateOOG40, "
			+ " TO_CHAR(SAILING_DT,'MM/DD/YYYY') sailingdt,created_by,thcd20,thcd40,thcm20,thcm40 from ( "
			+ " "
			+ "  select * from quatity_rate_report "
			+ " ) a";
	
	public static String QUATITY_VS_RATE_ll = 
			 "SELECT quotationno, "
			+ "       mloshortname, "
			+ "       To_char(valid_till, 'DD/MM/YYYY')   validto, "
			+ "       To_char(valid_from, 'DD/MM/YYYY')   validfrom, "
			+ "       rated20, "
			+ "       rated40, "
			+ "       quatityd20, "
			+ "       quatityd40, "
			+ "       ratem20, "
			+ "       ratem40, "
			+ "       quatitym20, "
			+ "       quatitym40, "
			+ "       rater20, "
			+ "       rater40, "
			+ "       quatityr20, "
			+ "       quatityr40, "
			+ "       quatityoog20, "
			+ "       quatityoog40, "
			+ "       To_char(quotation_dt, 'MM/DD/YYYY') quotationdt, "
			+ "       pol, "
			+ "       pod, "
			+ "       Upper(quotationtype)                quotationType, "
			+ "       sector, "
			+ "       rateoog20, "
			+ "       rateoog40, "
			+ "       To_char(sailing_dt, 'MM/DD/YYYY')   sailingdt, "
			+ "       created_by "
			+ "FROM   (SELECT quotationno, "
			+ "               mloshortname, "
			+ "               a.pol, "
			+ "               a.pod, "
			+ "               quotation_dt, "
			+ "               valid_from, "
			+ "               valid_till, "
			+ "               sailing_dt, "
			+ "               rated20, "
			+ "               rated40, "
			+ "               ratem20, "
			+ "               ratem40, "
			+ "               rater20, "
			+ "               rater40, "
			+ "               rateoog20, "
			+ "               rateoog40, "
			+ "               quatityd20, "
			+ "               quatityd40, "
			+ "               quatitym20, "
			+ "               quatitym40, "
			+ "               quatityr20, "
			+ "               quatityr40, "
			+ "               quotation_no, "
			+ "               quotationtype, "
			+ "               sector, "
			+ "               quatityoog20, "
			+ "               quatityoog40, "
			+ "               created_by "
			+ "        FROM   (SELECT quotation.quotation_no   quotationNo, "
			+ "                       quotation.created_by, "
			+ "                       mlo_short_name           mloshortname, "
			+ "                       quotation_port_pair.pol, "
			+ "                       quotation_port_pair.pod, "
			+ "                       quotation_dt, "
			+ "                       valid_from, "
			+ "                       valid_till, "
			+ "                       rated20, "
			+ "                       rated40, "
			+ "                       ratem20, "
			+ "                       ratem40, "
			+ "                       rater20, "
			+ "                       rater40, "
			+ "                       rateoog20, "
			+ "                       rateoog40, "
			+ "                       quotation.quotation_type quotationType, "
			+ "                       sector "
			+ "                FROM   (select quotation_no,qpp_id,ofd20  rated20, "
			+ "                      ofd40 rated40, "
			+ "                      ofm20 ratem20, "
			+ "                     ofm40  ratem40, "
			+ "                    ofr20   rater20, "
			+ "                      ofr40 rater40, "
			+ "                     oogd20  rateoog20, "
			+ "                     oogd40  rateoog40 from  quot_cont_charges_view) QUOTATION_CONTAINER_CHARGES "
			+ "                       INNER JOIN quotation_port_pair "
			+ "                               ON QUOTATION_CONTAINER_CHARGES.quotation_no = "
			+ "                                  quotation_port_pair.quotation_no "
			+ "                                  AND QUOTATION_CONTAINER_CHARGES.qpp_id = "
			+ "                                      quotation_port_pair.qpp_id "
			+ "                       INNER JOIN quotation "
			+ "                               ON quotation.quotation_no = "
			+ "                                  quotation_port_pair.quotation_no "
			+ "                       LEFT JOIN mlo_master "
			+ "                              ON mlo_code = mlo_id) a, "
			+ "               (SELECT Sum(d20)   quatityD20, "
			+ "                       Sum(d40)   quatityD40, "
			+ "                       Sum(m20)   quatityM20, "
			+ "                       Sum(m40)   quatityM40, "
			+ "                       Sum(r20)   quatityR20, "
			+ "                       Sum(r40)   quatityR40, "
			+ "                       quotation_no, "
			+ "                       pol, "
			+ "                       pod, "
			+ "                       Sum(oog20) quatityOOG20, "
			+ "                       Sum(oog40) quatityOOG40, "
			+ "                       sailing_dt "
			+ "                FROM   (SELECT loading_id, "
			+ "                               d20, "
			+ "                               d40, "
			+ "                               d45, "
			+ "                               m20, "
			+ "                               m40, "
			+ "                               m45, "
			+ "                               r20, "
			+ "                               r40, "
			+ "                               oog20, "
			+ "                               oog40, "
			+ "                               approved_by, "
			+ "                               quotation_no, "
			+ "                               pol, "
			+ "                               pod, "
			+ "                               sailing_dt "
			+ "                        FROM   loading_summary loading, "
			+ "                               (SELECT BL.loading_no, "
			+ "                                       BL.bl_no, "
			+ "                                       DTL.invoice_no, "
			+ "                                       HDR.quotation_no, "
			+ "                                       HDR.total, "
			+ "                                       hdr.invoice_dt, "
			+ "                                       HDR.agent "
			+ "                                FROM   singleinvoice_bl_dtl DTL, "
			+ "                                       singleinvoice_hdr HDR, "
			+ "                                       bill_of_lading_hdr BL "
			+ "                                WHERE  DTL.invoice_no = HDR.invoice_no "
			+ "                                       AND BL.bl_no = DTL.bl_no) INVOICE "
			+ "                        WHERE  loading.loading_id = INVOICE.loading_no "
			+ "                               AND approved_by IS NOT NULL) x "
			+ "                GROUP  BY x.quotation_no, "
			+ "                          pol, "
			+ "                          pod, "
			+ "                          sailing_dt) b "
			+ "        WHERE  a.quotationno = b.quotation_no "
			+ "               AND a.pol = b.pol "
			+ "               AND a.pod = b.pod) a";

	public static String GET_QUATITY = "select sum(NO_OF_Teus) NO_OF_Teus from loading  where pol=? and pod=? "
			+ " and get_company(MLO)=? and SAILING_DT >=to_date(?,'DD/MM/YYYY') "
			+ " and  SAILING_DT <=to_date(?,'MM/DD/YYYY')  and APPROVED_BY is not null ";

	public static String GET_QUOTATION = "select quotation_no  from quotation where active='Y'";
	
	
	public static String GET_INVOICE_VALUES="SELECT  Sum(d20)   quatityD20, "
			+ "			                       Sum(d40)   quatityD40, "
			+ "			                       Sum(m20)   quatityM20, "
			+ "			                       Sum(m40)   quatityM40, "
			+ "			                       Sum(r20)   quatityR20, "
			+ "			                       Sum(r40)   quatityR40, "
			+ "			                       quotation_no, "
			+ "			                       pol, "
			+ "			                       pod, "
			+ "			                       Sum(oog20) quatityOOG20, "
			+ "			                       Sum(oog40) quatityOOG40, "
			+ "			                       sailing_dt "
			+ "			                        FROM   loading_summary loading, "
			+ "			                               (SELECT BL.loading_no, "
			+ "			                                       BL.bl_no, "
			+ "			                                       DTL.invoice_no, "
			+ "			                                       HDR.quotation_no, "
			+ "			                                       HDR.total, "
			+ "			                                       hdr.invoice_dt, "
			+ "			                                       HDR.agent "
			+ "			                                FROM   singleinvoice_bl_dtl DTL, "
			+ "			                                       singleinvoice_hdr HDR, "
			+ "			                                       bill_of_lading_hdr BL "
			+ "			                                WHERE  DTL.invoice_no = HDR.invoice_no "
			+ "			                                       AND BL.bl_no = DTL.bl_no) INVOICE "
			+ "			                        WHERE  loading.loading_id = INVOICE.loading_no "
			+ "			                               AND approved_by IS NOT NULL   ";
	
	public static String GET_QUOTATION_DATA="select  quotation.quotation_no   quotationNo, "
			+ "			                       quotation.created_by, "
			+ "			                       mlo_short_name           mloshortname, "
			+ "			                       quotation_port_pair.pol, "
			+ "			                       quotation_port_pair.pod, "
			+ "			                       quotation_dt, "
			+ "			                       valid_from, "
			+ "			                       valid_till, "
			+ "			                       ofd20  rated20, "
			+ "			                      ofd40 rated40, "
			+ "			                      ofm20 ratem20, "
			+ "			                     ofm40  ratem40, "
			+ "			                    ofr20   rater20, "
			+ "			                      ofr40 rater40, "
			+ "			                     oogd20  rateoog20, "
			+ "			                     oogd40  rateoog40 , "
			+ "			                       quotation.quotation_type quotationType, "
			+ "			                       sector  from quot_cont_charges_view qcc "
			+ "			                           INNER JOIN quotation_port_pair "
			+ "			                               ON qcc.quotation_no = "
			+ "			                                  quotation_port_pair.quotation_no "
			+ "			                                  AND qcc.qpp_id = "
			+ "			                                      quotation_port_pair.qpp_id "
			+ "			                       INNER JOIN quotation "
			+ "			                               ON quotation.quotation_no = "
			+ "			                                  quotation_port_pair.quotation_no "
			+ "			                       INNER JOIN mlo_master "
			+ "			                              ON mlo_code = mlo_id where quotation.quotation_no is not null";

}
