package com.dci.tenant.finance.salesorder;

public class SalesOrderQueryUtil {
	public static final String GET_COMPANY_LIST = "select company_id as haspitalCode,company_name as haspitalName from company order by company_name";
	public static final String GET_EMPLOYEE_LIST = "select e.employee_id as employeeId,e.first_name as employeeName" + ",e.middle_name,e.surname,d.designation_id as jobTitleCode,d.designation_name as jobTitleName " + " from employee e join designation d on e.designation_id=d.designation_id order by e.first_name";

	public static final String GET_CITY_LIST = "select c.city_id as billingCityCode,c.city_name as billingCity,c.state_code as billingStateCode,s.state_name as billingState," + "c.pincode as  billingPinCode,s.country_code as billingCountryCode,con.country_name as billingCountry from city c " + " join state s on c.state_Code=s.state_code " + " join country con on s.country_code=con.country_code";
	public static final String GET_CITY_LIST1 = "select c.city_id as deliveryCityCode,c.city_name as deliveryCity,c.state_code as deliveryStateCode,s.state_name as deliveryState," + "c.pincode as  deliveryPinCode,s.country_code as deliveryCountryCode,con.country_name as deliveryCountry from city c " + " join state s on c.state_Code=s.state_code " + " join country con on s.country_code=con.country_code";
	public static final String GET_CUSTOMER_LIST = "select entity_id as customerCode,entity_name as  customerName,contact_person as contactPerson," + "job_position as jobTitleName,a.street as billingAddress,c.city_id as billingCityCode,c.city_name as billingCity,s.state_name as billingState,con.country_name as billingCountry," + "c.pincode as billingPinCode from entity e left join address a on e.address_id=a.address_id " + " left join city c on c.city_id=a.city_id " + " left join state s on s.state_code=c.state_code "
			+ " left join country con on con.country_code=s.country_code inner join employee em on em.employee_id = e.created_by inner join branch_department bd on bd.branch_department_id = em.branch_department_id inner join branch b on b.branch_id = bd.branch_id where e.is_customer='t'  and e.is_active=true and b.company_id = ? ";

	public static final String GET_ITEM_LIST = "select i.item_id  id,i.item_code||'-'|| i.item_name as text, i.item_id as itemId,i.item_code as itemCode,i.item_code||'-'|| i.item_name as itemName,i.item_description as itemDescription, i.item_Category as itemCategoryId, " + "ic.category_name as itemCategory,coalesce(sales_tax,0) as taxId,tax_name as taxCode from item_new " + "i  join item_Category ic on i.item_Category=ic.item_Category_id left join item_category_account ica on ica.item_category_id = i.item_category "
			+ "left join tax on tax.tax_id = ica.sales_tax where i.is_saleable=true and i.company_id = ? order by i.item_name asc";

	public static final String GET_TAX_LIST = "select tax_id as taxId,tax_code as taxCode,tax_amount as taxAmount,tax_percentage as taxPercent from tax";
	public static final String GENERATE_SALES_ORDER_CODE = "SELECT CASE WHEN MAX(sales_order_code) IS NULL THEN 'SO00001' ELSE rpad(MAX(sales_order_code),5,'SO')|| " + " lpad(cast(cast((SUBSTRING(MAX(sales_order_code),5)) as int)+1 " + " as text),4,'0') END FROM sales_order where sales_order_code like 'SO%'";
	public static final String SAVE_SALES_ORDER_HDR = "INSERT INTO sales_order( sales_order_code, sales_order_date, company_code, " + " created_by, customer_id, customer_note, status,total_tax_amount,total_amount,net_amount)   VALUES (?, to_date(?,'dd/mm/yyyy'), ?, ?, ?, ?, ?,?, ?, ?) returning sales_order_id";
	public static final String SAVE_SALES_ORDER_DTL = "INSERT INTO sales_order_detail(sales_order_id,item_id, quantity, unit_price, tax_amount," + " tax_id, amount)   VALUES (?,?, ?, ?, ?, ?, ?)";
	public static final String GET_SALES_ORDER_LIST = "select sales_order_id as salesOrderId,sales_order_code as salesOrderNo,TO_CHAR(sales_order_date,'DD/MM/YYYY')  as salesOrderDate,company_code as companyCode,en.contact_person as contactPerson, so.created_by as createdBy," + "customer_id as customerCode, customer_note as customerNote, so.status as status,c.company_name as haspitalName"
			+ ",e.first_name as employeeName,en.entity_name as customerName,COALESCE(total_tax_amount,0) as totalTax,COALESCE(total_amount,0) as totalAmount,COALESCE( net_amount,0) as netAmount" + " from sales_order so join company c on so.company_code =c.company_id " + " join employee e on e.employee_id=so.created_by join entity en on en.entity_id=so.customer_id order by sales_order_code desc";

	public static final String EDIT_SALES_ORDER_HDR = "select sales_order_id as salesOrderId,sales_order_code as salesOrderNo,to_char(sales_order_date,'DD/MM/YYYY') as salesOrderDate,company_code as haspitalCode " + " ,COALESCE(customer_id,0) as customerCode,created_By as employeeId,customer_note as customerNote,status as status,COALESCE(total_tax_amount,0) as totalTax, " + " COALESCE(total_amount,0) as totalAmount,COALESCE(net_amount,0) as netAmount from sales_order where sales_order_id=?";
	public static final String EDIT_SALES_ORDER_DTL = "SELECT sod.sales_order_dtl_id as salesOrderDtlId, COALESCE(tax.tax_percentage,0) as taxPercent, COALESCE(sod.item_id,0) as itemId,i.item_code as itemCode,i.item_code||'-'|| i.item_name as itemName,i.item_description as itemDesc,COALESCE(sod.quantity,0) as qty, COALESCE(sod.unit_price,0) as price, COALESCE(sod.tax_amount,0) as taxAmount,COALESCE(sod.tax_id,0) as taxId, COALESCE(sod.amount,0) as amount,i.item_Category as itemCategoryId,ic.category_name as itemCategory,sales_tax as taxId,tax_name as taxCode FROM sales_order_detail sod inner join item_new i on i.item_id = sod.item_id left join item_Category ic on i.item_Category=ic.item_Category_id left join item_category_account ica on ica.item_category_id = i.item_category left join tax on tax.tax_id = ica.sales_tax where sod.sales_order_id=? order by sod.sales_order_dtl_id asc";

	public static final String UPDATE_SALES_ORDER_HDR = "UPDATE sales_order   SET  sales_order_date=to_date(?,'dd/mm/yyyy'), company_code=?," + "created_by=?, customer_id=?, customer_note=?, status=?, total_tax_amount=?," + "total_amount=?, net_amount=?  WHERE sales_order_id=?";
	public static final String UPDATE_SALES_ORDER_DTL = "UPDATE sales_order_detail   SET  item_id=?, quantity=?, unit_price=?, tax_amount=?," + "tax_id=?, amount=? WHERE sales_order_dtl_id=?";

	public static final String DELETE_SALES_ORDER_DTL = "delete from sales_order_detail where sales_order_id=?";
	public static final String DELETE_SALES_ORDER_HDR = "delete from sales_order  where sales_order_id=?";

}
