package com.dci.tenant.finance.balanceSheet;

public class BalanceSheetQueryUtil {

	public static String GET_COMPANY_LIST = "select company_id as id, company_name as text from company";

	public static String GET_PROFIT_OR_LOSS = " SELECT coalesce((sum(debit)-sum(credit)),0) AS balance from " + " (select gh.group_head_code,gh.group_head_name,gh.group_head_code,sum(gl.bc_credit) as credit, " + "  sum(gl.bc_debit) as debit,gl.company_id from (sub_group_acct_master sga inner join " + "  group_head_master gh on sga.group_head_code =gh.group_head_code) " + " inner join general_ledger gl on sga.sub_group_acct_code = gl.parent_code "
			+ " where gl.ledger_date <= ? and gl.company_id = ?    and gl.cost_center in (?) and (gh. group_head_code='I' or gh. group_head_code='E')  " + " group by gh.group_head_code,gh.group_head_name,gh.group_head_code,gl.company_id " + " order by gh.group_head_code) pl";

	public static String GET_PROFIT_OR_LOSS_1 = " SELECT coalesce((sum(debit)-sum(credit)::numeric),0) AS balance from " + " (select gh.group_head_code,gh.group_head_name,gh.group_head_code,sum(gl.bc_credit) as credit, " + "  sum(gl.bc_debit) as debit,gl.company_id from (sub_group_acct_master sga inner join " + "  group_head_master gh on sga.group_head_code =gh.group_head_code) " + " inner join general_ledger gl on sga.sub_group_acct_code = gl.parent_code "
			+ " where gl.ledger_date <= ? and gl.company_id = ?    and gl.cost_center = ? and (gh. group_head_code='I' or gh. group_head_code='E') " + " group by gh.group_head_code,gh.group_head_name,gh.group_head_code,gl.company_id " + " order by gh.group_head_code) pl";

	public static String GET_BALANCE_SHEET_HDR = " SELECT group_head_master.group_head_code as groupHeadCode,group_head_master.group_head_name as groupHeadName, " + " group_head_master.group_head_code as groupHeadType, " + " (select case when group_head_master.group_head_code='A' then " + " sum(general_ledger.bc_credit) - sum(general_ledger.bc_debit) else " + " sum(general_ledger.bc_debit) - sum(general_ledger.bc_credit) end ) as amount " + " FROM   (general_ledger  INNER JOIN sub_group_acct_master ON "
			+ " general_ledger.parent_code=sub_group_acct_master.sub_group_acct_code) " + " INNER JOIN group_head_master ON " + " sub_group_acct_master.group_head_code=group_head_master.group_head_code" + " WHERE  (group_head_master.group_head_code='A' OR group_head_master.group_head_code='L') " + " and general_ledger.ledger_date<= ? and  general_ledger.company_id= ?   and cost_center = ? " + " group by  group_head_master.group_head_code,group_head_master.group_head_name,group_head_master.group_head_code " + "   order by group_head_master.group_head_code ";

	public static String GET_PROFITLOSS_WITH_ACCOUNTCODE = " select '' AS groupHeadCode, case when balance >0 then 'Profit' else 'Loss' end as groupHeadName, " + " coalesce(balance,0) AS amount from (select (sum(debit)-sum(credit)) balance from (select gh.group_head_code,gh.group_head_name, " + " gh.group_head_code,sum(gl.bc_credit) as credit, sum(gl.bc_debit) as debit,gl.company_id from (sub_group_acct_master sga  " + " inner join group_head_master gh on sga.group_head_code =gh.group_head_code) "
			+ " inner join general_ledger gl on sga.sub_group_acct_code = gl.parent_code " + " where gl.ledger_date < ? and gl.company_id = ? and (gh. group_head_code='I' or gh. group_head_code='E') " + " group by gh.group_head_code,gh.group_head_name,gh.group_head_code,gl.company_id order by gh.group_head_code) pl) plouter ";

	public static String GET_BALANCE_SHEET_DTL = " select parent_code as groupHeadCode, sub_group_acct_master.sub_group_acct_name as groupHeadName, case when group_head_master.group_head_code='A' then  sum(general_ledger.bc_credit) - sum(general_ledger.bc_debit) else  sum(general_ledger.bc_debit) - sum(general_ledger.bc_credit) end as balance from  (general_ledger INNER JOIN sub_group_acct_master ON " + " general_ledger.parent_code=sub_group_acct_master.sub_group_acct_code) " + " INNER JOIN group_head_master ON "
			+ " sub_group_acct_master.group_head_code=group_head_master.group_head_code " + " where parent_code like ? and general_ledger.ledger_date <= ? and general_ledger.company_id=? " + " group by parent_code,sub_group_acct_master.sub_group_acct_name,group_head_master.group_head_code order by parent_code ";

	public static String GET_BALANCE_SHEETAH_DTL = "select general_ledger.account_code  as groupHeadCode,coalesce(AH.acct_head_name,'')  || coalesce(cust.entity_name,'') || coalesce(supp.entity_name,'') as groupHeadName,(case when group_head_master.group_head_code='A' then  sum(general_ledger.bc_credit) - sum(general_ledger.bc_debit) else  sum(general_ledger.bc_debit) - sum(general_ledger.bc_credit) end) as balance from general_ledger left join account_head_master AH on AH.acct_head_code = general_ledger.account_code left join entity cust on cust.customer_acct_code = general_ledger.account_code left join entity supp on supp.supplier_acct_code = general_ledger.account_code INNER JOIN sub_group_acct_master ON  general_ledger.parent_code=sub_group_acct_master.sub_group_acct_code  INNER JOIN group_head_master ON  sub_group_acct_master.group_head_code=group_head_master.group_head_code where general_ledger.parent_code =? and general_ledger.ledger_date <= ? and general_ledger.company_id=? group by general_ledger.account_code,AH.acct_head_name,cust.entity_name,supp.entity_name,group_head_master.group_head_code  order by  account_code";

	public static String GET_BALANCE_SHEET_HDR_NEW = " SELECT group_head_master.group_head_code as groupHeadCode,group_head_master.group_head_name as groupHeadName, " + " group_head_master.group_head_code as groupHeadType, " + " (select case when group_head_master.group_head_code='A' then " + " sum(general_ledger.bc_credit) - sum(general_ledger.bc_debit) else " + " sum(general_ledger.bc_debit) - sum(general_ledger.bc_credit) end ) as amount " + " FROM   (general_ledger  INNER JOIN sub_group_acct_master ON "
			+ " general_ledger.parent_code=sub_group_acct_master.sub_group_acct_code) " + " INNER JOIN group_head_master ON " + " sub_group_acct_master.group_head_code=group_head_master.group_head_code" + " WHERE  (group_head_master.group_head_code=?) " + " and general_ledger.ledger_date<= ? and  general_ledger.company_id= ?  and cost_center = ? " + " group by  group_head_master.group_head_code,group_head_master.group_head_name,group_head_master.group_head_code " + "   order by group_head_master.group_head_code ";
}
