package com.dci.tenant.finance.paymentReport;

public class PaymentReportQueryUtil {

	public static final String GET_PENDING_PAYMENT_INVOICE_DETAILS = "select COALESCE(pur_invoice_no,'') as purInvoiceNo, TO_CHAR(invoice_dt,'DD/MM/YYYY') as purInvoiceDate,COALESCE(inv_amt_bc,0) invoiceBCAmt, " + "COALESCE(inv_amt_tc,0) invoiceTCAmt, COALESCE(currency,'') currencyCode, COALESCE(exg_rate,0) exchangeRate,  " + "COALESCE(paid_amt_bc,0) paidAmountBC, COALESCE(paid_amt_tc,0) paidAmountTC, COALESCE(bc_balance_amt,0) AS bcBalanceAmt,  "
			+ "COALESCE(tc_balance_amt,0) tcBalanceAmt from (select aaa.pur_invoice_no, aaa.invoice_dt, aaa.inv_amt_bc,aaa.inv_amt_tc, aaa.currency, aaa.exg_rate, " + "aaa.paid_amt_bc, aaa.paid_amt_tc, (aaa.inv_amt_bc-aaa.paid_amt_bc)  bc_balance_amt, (aaa.inv_amt_tc - aaa.paid_amt_tc) tc_balance_amt " + "from (select  cbpinv.pur_invoice_no, pih.invoice_dt, cbpinv.inv_amt_bc,cbpinv.inv_amt_tc, cbpinv.currency, cbpinv.exg_rate, sum(cbpinv.paid_amt_bc) paid_amt_bc, "
			+ "sum(cbpinv.paid_amt_tc) paid_amt_tc from cashbank_pay_inv_dtl cbpinv left join purchase_invoice_hdr pih on pih.invoice_no = cbpinv.pur_invoice_no " + "group by cbpinv.pur_invoice_no,pih.invoice_dt,cbpinv.inv_amt_bc,cbpinv.inv_amt_tc,cbpinv.currency,cbpinv.exg_rate) aaa " + "where aaa.pur_invoice_no in (select invoice_no from purchase_invoice_hdr where  payment_status not like 'Fully Paid%') and (aaa.inv_amt_bc-aaa.paid_amt_bc)>0 "
			+ "group by pur_invoice_no,invoice_dt,inv_amt_bc,inv_amt_tc,currency,exg_rate, paid_amt_bc,paid_amt_tc union " + "select pih.invoice_no,  pih.invoice_dt,pih.amount as inv_amt_bc, pih.tc_amount as inv_amt_tc,pih.currency, pih.ex_rate as exg_rate, 0 as paid_amt_bc,0 as paid_amt_tc, " + "pih.amount as bc_balance_amt, pih.tc_amount as tc_balance_amt from purchase_invoice_hdr pih where  payment_status not like 'Fully Paid%' " + "and pih.invoice_no not in(select pur_invoice_no from cashbank_pay_inv_dtl)) T1 order by purInvoiceNo desc";

	public static final String list = "select invoice_no purInvoiceNo, to_char(invoice_dt,'DD/MM/YYYY') as purInvoiceDate," + " " + "entity.entity_id  as supplierCode, entity.entity_name as supplierName, purchase_invoice_hdr.currency  currency," + "" + " to_char(due_dt, 'DD/MM/YYYY') dueDate, COALESCE(amount,0) as bcAmountHdr,COALESCE(amount,0) invoiceBCAmt," + "" + " COALESCE(tc_amount,0) as tcAmountHdr from purchase_invoice_hdr left join entity on entity.entity_id::text = purchase_invoice_hdr.supplier";

	public static String search_list = "select invoice_no purInvoiceNo, to_char(invoice_dt,'DD/MM/YYYY') as purInvoiceDate," + " " + "entity.entity_id  as supplierCode, entity.entity_name as supplierName, purchase_invoice_hdr.currency  currency," + "" + " to_char(due_dt, 'DD/MM/YYYY') dueDate, COALESCE(amount,0) as bcAmountHdr,COALESCE(amount,0) invoiceBCAmt," + "" + " COALESCE(tc_amount,0) as tcAmountHdr from purchase_invoice_hdr left join entity on entity.supplier_acct_code = purchase_invoice_hdr.supplier where 1=1 ";

	public static final String list_new = "select invoice_no purInvoiceNo, to_char(invoice_dt,'DD/MM/YYYY') as purInvoiceDate,entity.entity_id  as supplierCode, entity.entity_name as supplierName, purchase_invoice_hdr.currency  currency, to_char(due_dt, 'DD/MM/YYYY') dueDate, COALESCE(amount,0) as bcAmountHdr,COALESCE(amount,0) invoiceBCAmt,COALESCE(tc_amount,0) as tcAmountHdr from purchase_invoice_hdr left join entity on entity.supplier_acct_code = purchase_invoice_hdr.supplier where 1=1 union 	select invoice_no purInvoiceNo, to_char(invoice_dt,'DD/MM/YYYY') as purInvoiceDate,entity.entity_id  as supplierCode, entity.entity_name as supplierName, general_purchase_invoice_hdr.currency  currency, '', COALESCE(amount,0) as bcAmountHdr,COALESCE(amount,0) invoiceBCAmt, 0 from general_purchase_invoice_hdr left join entity on entity.supplier_acct_code = general_purchase_invoice_hdr.supplier where 1=1";
	public static final String list1 = "union 	select invoice_no purInvoiceNo, to_char(invoice_dt,'DD/MM/YYYY') as purInvoiceDate,entity.entity_id  as supplierCode, entity.entity_name as supplierName, general_purchase_invoice_hdr.currency  currency, '', COALESCE(amount,0) as bcAmountHdr,COALESCE(amount,0) invoiceBCAmt, 0  from general_purchase_invoice_hdr left join entity on entity.supplier_acct_code = general_purchase_invoice_hdr.supplier where 1=1";
}
